#! /bin/bash
set -x 
TRUNK=${1:-trunk}
BRANCH=$(hg branch)
hg pull -b "$TRUNK" &&
hg pull -b "$BRANCH" &&
hg up -C "$TRUNK" &&
hg merge "$BRANCH"
hg branch "$BRANCH"
hg id
other/libre/libre.py build-eclipse
